### PR TITLE
Add support for PHP8 and update tests to work with newer phpunit

### PR DESCRIPTION
**Pull request by GasparMDQ**
I allowed for PHP 8 to be used and upgrade PHPUnit to a version compatible with it. I had to match the return type of some of the PHPUnit functions.

### CODE REVIEW

**Comment by GasparMDQ** [comment]
This PR closes #31

**Comment by mjaschen** [comment]
@andrmoel Do you have any plans to merge this PR?

**Comment by andrmoel** [comment]
Looks good and I will merge.
Sorry but I rarely use PHP atm

**Comment by mjaschen** [comment]
Thanks a lot!

Would you mind tagging a new version so that Packagist is able to pick up?

**Pull request merged**
